[package]
name = "rskj-bn128"
version = "0.1.0"
authors = ["mraof <mraof@mraof.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-bn = "0.4"
jni = "0.13"
byteorder = "1"